/**
 * Render `VERIFY_STEPS` as the numbered list in `INSTALL.md`, between the two marker comments.
 * The section is a build output that happens to be committed: `check:verify-steps-doc` fails
 * when it is stale.
 */
const { VERIFY_STEPS } = require('./verifySteps')

const DOC_FILE = 'INSTALL.md'
const START_MARKER = '<!-- verify-steps:start (generated by `pnpm run generate:verify-steps-doc`) -->'
const END_MARKER = '<!-- verify-steps:end -->'

/**
 * @param {ReadonlyArray<import('./verifySteps').VerifyStep>} [steps]
 * @returns {string}
 */
function renderVerifySteps(steps = VERIFY_STEPS) {
  const items = steps.map(
    ({ label, script, why }, index) => `${index + 1}. **${label}** (\`pnpm run ${script}\`): ${why}`
  )
  return [START_MARKER, ...items, END_MARKER].join('\n')
}

/**
 * Replace the marked section of `content` with a freshly rendered one.
 *
 * @param {string} content
 * @param {string} [rendered]
 * @returns {string}
 */
function replaceVerifyStepsSection(content, rendered = renderVerifySteps()) {
  const start = content.indexOf(START_MARKER)
  const end = content.indexOf(END_MARKER)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${DOC_FILE} is missing the verify-steps markers`)
  }
  return content.slice(0, start) + rendered + content.slice(end + END_MARKER.length)
}

module.exports = { DOC_FILE, END_MARKER, START_MARKER, renderVerifySteps, replaceVerifyStepsSection }
