/**
 * Files rendered from `ENV_CATALOG` (#31): `.env.example` (whole file) and the placement table in
 * `docs/SECRETS-AND-ENVIRONMENT.md` (between two marker comments). Both are build outputs that
 * happen to be committed: `check:env-contract` fails when either is stale, and
 * `npm run generate:env-docs` rewrites them.
 */
const fs = require('node:fs')
const path = require('node:path')
const { ENV_CATALOG, EXAMPLE_GROUPS } = require('./envCatalog')

const EXAMPLE_FILE = '.env.example'
const DOC_FILE = 'docs/SECRETS-AND-ENVIRONMENT.md'
const START_MARKER = '<!-- env-catalog:start (generated by `npm run generate:env-docs`) -->'
const END_MARKER = '<!-- env-catalog:end -->'

const CODE_DIRS = ['app', 'lib', 'scripts']
const CODE_FILES = ['instrumentation.ts', 'instrumentation-client.ts', 'next.config.js']
const CODE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.mjs', '.cjs'])
const ENV_READ = /process\.env(?:\.([A-Z_][A-Z0-9_]*)|\[['"]([A-Z_][A-Z0-9_]*)['"]\])/g

/** @param {import('./envCatalog').EnvVar[]} [catalog] */
function renderEnvExample(catalog = ENV_CATALOG) {
  const lines = [
    '# Names only, never values (#31). Generated from scripts/lib/envCatalog.js by',
    '# `npm run generate:env-docs`; edit the catalog, not this file.',
    '#',
    '# The master .env.local lives in the main checkout only; worktrees read it from there.',
    '# Where each name belongs: docs/SECRETS-AND-ENVIRONMENT.md',
  ]
  for (const group of EXAMPLE_GROUPS) {
    const entries = catalog.filter((entry) => entry.group === group && entry.local !== 'none')
    if (entries.length === 0) continue
    lines.push('', `# ${group}`)
    for (const entry of entries) {
      const tags = [entry.local, entry.secret ? 'secret' : null].filter(Boolean).join(', ')
      lines.push(`# ${entry.purpose} (${tags})`, `${entry.name}=`)
    }
  }
  return `${lines.join('\n')}\n`
}

/** @param {ReadonlyArray<string>} list */
function cell(list) {
  return list.length > 0 ? list.join(', ') : '—'
}

/**
 * @param {import('./envCatalog').EnvVar[]} [catalog]
 * @param {Map<string, string[]>} [usage] name → files that read it
 */
function renderCatalogTable(catalog = ENV_CATALOG, usage = new Map()) {
  const rows = [
    '| Name | Purpose | Secret | Source | Local | Vercel | GitHub | Cloud Run | Read by |',
    '|---|---|---|---|---|---|---|---|---|',
  ]
  for (const entry of catalog) {
    const readBy = (usage.get(entry.name) ?? []).map((file) => `\`${file}\``)
    rows.push(
      `| \`${entry.name}\` | ${entry.purpose} | ${entry.secret ? 'yes' : 'no'} | ${entry.source} | ` +
        `${entry.local} | ${cell(entry.vercel)} | ${cell(entry.github)} | ${cell(entry.cloudRun)} | ` +
        `${readBy.length > 0 ? readBy.join(', ') : '—'} |`
    )
  }
  return [START_MARKER, ...rows, END_MARKER].join('\n')
}

/**
 * @param {string} content
 * @param {string} rendered
 */
function replaceCatalogSection(content, rendered) {
  const start = content.indexOf(START_MARKER)
  const end = content.indexOf(END_MARKER)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${DOC_FILE} is missing the env-catalog markers`)
  }
  return content.slice(0, start) + rendered + content.slice(end + END_MARKER.length)
}

/** @param {string} dir @param {string} root @returns {string[]} */
function walk(dir, root) {
  const absolute = path.join(root, dir)
  if (!fs.existsSync(absolute)) return []
  return fs.readdirSync(absolute, { withFileTypes: true }).flatMap((dirent) => {
    const relative = path.join(dir, dirent.name)
    if (dirent.isDirectory()) return dirent.name === 'node_modules' ? [] : walk(relative, root)
    return CODE_EXTENSIONS.has(path.extname(dirent.name)) ? [relative] : []
  })
}

/**
 * Every `process.env` name the code reads, with the files that read it.
 *
 * @param {string} root
 * @returns {Map<string, string[]>}
 */
function scanEnvUsage(root) {
  /** @type {Map<string, string[]>} */
  const usage = new Map()
  const files = [...CODE_DIRS.flatMap((dir) => walk(dir, root)), ...CODE_FILES].filter((file) =>
    fs.existsSync(path.join(root, file))
  )
  for (const file of files.sort()) {
    const content = fs.readFileSync(path.join(root, file), 'utf8')
    for (const match of content.matchAll(ENV_READ)) {
      const name = match[1] ?? match[2]
      const readers = usage.get(name) ?? []
      if (!readers.includes(file)) readers.push(file)
      usage.set(name, readers)
    }
  }
  return usage
}

module.exports = {
  DOC_FILE,
  END_MARKER,
  EXAMPLE_FILE,
  START_MARKER,
  renderCatalogTable,
  renderEnvExample,
  replaceCatalogSection,
  scanEnvUsage,
}
